name: mhc-genotyping
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core tools
  - python>=3.9,<4
  - nextflow>=21.04.0
  
  # Bioinformatics tools
  - vsearch>=2.21.0
  - bbmap>=39.00
  - seqkit>=2.10.0,<3
  - samtools>=1.17
  - pigz
  
  # Python packages
  - pandas>=1.5.0
  - pip
  
  # Install additional Python packages via pip
  - pip:
    - pysam>=0.21.0
    - xlsxwriter>=3.0.0
    - biopython>=1.80
    - openpyxl>=3.0.0
    - numpy>=1.21.0